In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
370,ham,Hello my boytoy ... Geeee I miss you already a...,NaN,NaN,NaN
298,ham,I cant pick the phone right now. Pls send a me...,NaN,NaN,NaN
311,spam,Think ur smart ? Win å£200 this week in our we...,NaN,NaN,NaN
975,ham,Hey no I ad a crap nite was borin without ya 2...,NaN,NaN,NaN
4623,ham,Jus finish blowing my hair. U finish dinner al...,NaN,NaN,NaN

In [3]:
df.shape

(5572, 5)

In [ ]:
#STEPS TO BUILD A MACHINE LEARNING MODEL
#1 Data Cleaning
#2 EDA
#3 Text Preprocessing
#4 Model Building
#5 Evaluation
#6 Improvement
#7 Website
#8 Deploy

1. Data Cleaning

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [5]:
#Drop last 3 columns which are not required since they have missing values
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)
df.sample(5)

        v1                                                 v2
4916  spam  This is the 2nd time we have tried 2 contact u...
4895   ham       2 and half years i missed your friendship:-)
4577  spam  Urgent! call 09066350750 from your landline. Y...
697    ham  meet you in corporation st outside gap Û_ you...
2110   ham                Do we have any spare power supplies

In [6]:
#Renaming the columns
df.rename(columns={'v1': 'target', 'v2': 'text'}, inplace=True)
df.sample(5)

     target                                               text
3729    ham  I guess you could be as good an excuse as any,...
4670    ham  Probably not, I'm almost out of gas and I get ...
2840    ham                                        Ok thanx...
39      ham  Hello! How's you and how did saturday go? I wa...
2800    ham                      Depends on where u going lor.

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [9]:
df['target'] = encoder.fit_transform(df['target'])

In [10]:
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [11]:
#missing values
df.isnull().sum()

target    0
text      0
dtype: int64

In [12]:
# check for duplicate values
df.duplicated().sum()

np.int64(403)

In [13]:
#remove duplicates
df.drop_duplicates(keep='first', inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.shape

(5169, 2)

#2. EDA